- name: Configurar servidor web, Docker y desplegar Aplicacion CRUD
  hosts: web_server
  become: yes

  tasks:
    - name: Actualizar todos los paquetes del sistema operativo (DNF)
      dnf:
        name: "*"
        state: latest

    - name: Instalar el servicio de Docker
      dnf:
        name: docker
        state: present

    - name: Habilitar y encender el servicio de Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Agregar al usuario ec2-user al grupo de docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Crear la carpeta base de la aplicación en /opt/app
      file:
        path: /opt/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    # ==========================================================
    # DESPLIEGUE DE LA APLICACIÓN (CRUD + PHPMyAdmin)
    # ==========================================================

    - name: Asegurar que aws-cli está instalado en el servidor
      dnf:
        name: awscli
        state: present

    - name: Descargar paquete de la app desde S3 usando aws-cli
      command: >
        aws s3 cp 
        s3://terraform-state-ec2-lab-141553305029-us-east-1-an/app-releases/{{ lookup('env', 'TARGET_ENV') }}/app-release.zip 
        /opt/app.zip
      environment:
        AWS_DEFAULT_REGION: us-east-1

    - name: Descomprimir la aplicación en /opt/app
      unarchive:
        src: /opt/app.zip
        dest: /opt/app/
        remote_src: yes

    - name: Crear archivo .env usando los secretos del pipeline
      copy:
        dest: /opt/app/.env
        content: |
          DB_HOST={{ lookup('env', 'RDS_ENDPOINT') }}
          DB_NAME={{ lookup('env', 'DB_NAME') }}
          DB_USER={{ lookup('env', 'DB_USER') }}
          DB_PASSWORD={{ lookup('env', 'DB_PASSWORD') }}
          APP_PORT={{ lookup('env', 'APP_PORT') }}
          PHPMYADMIN_PORT={{ lookup('env', 'PHPMYADMIN_PORT') }}
          APP_ENV={{ lookup('env', 'TARGET_ENV') }}
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Levantar contenedores con Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present
        build: always
        env_files:
          - .env