name: 1. Terraform Plan (Auto)

on:
  push:
    branches:
      - dev
      - pre

concurrency:
  group: terraform-plan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    name: Run Terraform Plan
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true
      TF_VAR_aws_region: us-east-1
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    defaults:
      run:
        working-directory: aws/environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.3

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: |
          terraform plan \
            -lock-timeout=5m \
            -out=tfplan

      # Guardamos el plan y el código de la app como artefactos en GitHub
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: aws/environments/dev/tfplan

      - name: Upload App Source
        uses: actions/upload-artifact@v4
        with:
          name: app-source-dev
          path: |
            app/
            docker-compose.yml